version: "3.8"

services:
  mariadb:
    image: mariadb:10.4
    container_name: database_mariadb
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=test_database"

  postgres:
    image: postgres:12
    container_name: database_postgres
    environment:
      - "POSTGRES_DB=test_database"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  database:
    build: ./
    container_name: database
    command: ci
    depends_on:
      - mariadb
      - postgres
    environment:
      - "MYSQL_HOST=database_mariadb"
      - "POSTGRES_HOST=database_postgres"
    restart: "no"
    volumes:
      - ./coverage:/app/coverage